### ISSUE TITLE
Persistent layer for threads data

### ISSUE THREAD

**Issue by mfominov** [42wim/matterbridge#1857] opened 2022-07-06 10:11 UTC
Hello. Thx for this project.

Our use case:
We created links between Teams channels off-topic/town square in same instance.

**Is your feature request related to a problem? Please describe.**
After restart of matterbridge it lost threads links/relation to parent message

**Describe the solution you'd like**
Maybe some persistent layer for storing this data.

**Describe alternatives you've considered**
Some kv storage

**Additional context**

**Comment by sas1024** [comment] 2022-07-06 11:09
Duplicate of https://github.com/42wim/matterbridge/issues/541 :)

**Closed** 2023-01-28 23:55 UTC
Labels: enhancement
