### ISSUE TITLE
matterbridge crashes when connecting to inspircd v3.2.0 using SASL

### ISSUE THREAD

**Issue by chotaire** [42wim/matterbridge#868] opened 2019-07-31 18:08 UTC
**Describe the bug**
matterbridge will crash when trying to SASL authenticate to an inspircd v3.2.0 server. This works fine when connecting to inspircd v2.0.27. UseSASL has to be set to false in order to connect. This is likely an issue with girc library. inspircd v3.2.0 is now using IRCv3.2 SASL, where a few things have changed. See https://ircv3.net/specs/extensions/sasl-3.2 for more information so @lrstanley may be interested to look into this. 

**To Reproduce**
- Install inspircd v3.2.0 and irc services (e.g. atheme) and create a user for SASL authentication
- configure an irc gateway for matterbridge and use UseSASL=true

**Expected behavior**
matterbridge should properly authenticate using SASL.

**Screenshots/debug logs**
Jul 31 19:56:42 rocketchat matterbridge-linux-amd64: time="2019-07-31T19:56:42+02:00" level=info msg="Running version 1.15.2-dev ff27746" prefix=main
Jul 31 19:56:42 rocketchat matterbridge-linux-amd64: time="2019-07-31T19:56:42+02:00" level=info msg="WARNING: THIS IS A DEVELOPMENT VERSION. Things may break." prefix=main
Jul 31 19:56:42 rocketchat matterbridge-linux-amd64: time="2019-07-31T19:56:42+02:00" level=info msg="Parsing gateway whatever" prefix=router
Jul 31 19:56:42 rocketchat matterbridge-linux-amd64: time="2019-07-31T19:56:42+02:00" level=info msg="Parsing gateway chotaire" prefix=router
Jul 31 19:56:42 rocketchat matterbridge-linux-amd64: time="2019-07-31T19:56:42+02:00" level=info msg="Starting bridge: irc.whatever " prefix=router
Jul 31 19:56:42 rocketchat matterbridge-linux-amd64: time="2019-07-31T19:56:42+02:00" level=info msg="Connecting 127.0.0.1:12345" prefix=irc
Jul 31 19:56:42 rocketchat matterbridge-linux-amd64: panic: runtime error: slice bounds out of range
Jul 31 19:56:42 rocketchat matterbridge-linux-amd64: goroutine 5 [running]:
Jul 31 19:56:42 rocketchat matterbridge-linux-amd64: github.com/lrstanley/girc.ParseEvent(0xc000416630, 0x30, 0x30)
Jul 31 19:56:42 rocketchat matterbridge-linux-amd64: /home/travis/gopath/pkg/mod/github.com/lrstanley/girc@v0.0.0-20190210212025-51b8e096d398/event.go:70 +0x987
Jul 31 19:56:42 rocketchat matterbridge-linux-amd64: github.com/lrstanley/girc.(*ircConn).decode(0xc000430000, 0xbf4893c1b1302a59, 0x45dd2fa5e3, 0x1d91520)
Jul 31 19:56:42 rocketchat matterbridge-linux-amd64: /home/travis/gopath/pkg/mod/github.com/lrstanley/girc@v0.0.0-20190210212025-51b8e096d398/conn.go:136 +0xaa
Jul 31 19:56:42 rocketchat matterbridge-linux-amd64: github.com/lrstanley/girc.(*Client).readLoop(0xc000352b60, 0x13f5180, 0xc000072080, 0xc000034180, 0xc000036060)
Jul 31 19:56:42 rocketchat matterbridge-linux-amd64: /home/travis/gopath/pkg/mod/github.com/lrstanley/girc@v0.0.0-20190210212025-51b8e096d398/conn.go:374 +0x1ca
Jul 31 19:56:42 rocketchat matterbridge-linux-amd64: created by github.com/lrstanley/girc.(*Client).internalConnect
Jul 31 19:56:42 rocketchat matterbridge-linux-amd64: /home/travis/gopath/pkg/mod/github.com/lrstanley/girc@v0.0.0-20190210212025-51b8e096d398/conn.go:282 +0x249
Jul 31 19:56:42 rocketchat systemd: matterbridge.service: main process exited, code=exited, status=2/INVALIDARGUMENT

**Environment (please complete the following information):**
 - OS: CentOS7
 - Matterbridge version: 1.15.2-dev ff27746

**Additional context**
<...>
[irc]
[irc.whatever]
Server="127.0.0.1:12345"
UseTLS=true
SkipTLSVerify=true
Nick="Rocket"
ColorNicks=true
ShowJoinPart=true
VerboseJoinPart=true
ShowTopicChange=true
RemoteNickFormat="<{NICK}> "
UseSASL=true
NickServNick="Rocket"
NickServPassword="42forthewim"
<...>

**Comment by lrstanley** [comment] 2019-07-31 18:22
girc should support the 3.2 spec of SASL. looks like it's failing to parse the incoming event, which is extremely odd, because nothing with sasl should affect that. Will look further when I get home.

Is there a way to print the raw incoming irc events/messages? Will need this to debug.

**Comment by chotaire** [comment] 2019-07-31 18:55
I will try if I can get those raw messages for you. In the meantime I got this from inspircd devs:

 20:50:50 <Clarus> Chotaire: This is a client parser bug. Please make sure you are on the latest version of your client and if you are please report it to the developer of your client. We unfortunately can't work around this due to the reasons specified here: https://github.com/inspircd/inspircd/issues/1636#issuecomment-490224949.

**Comment by 42wim** [comment] 2019-07-31 20:26
@chotaire add `debuglevel=1` to your `[irc.whatever]` to see more debug (also start with `-debug` flag)

**Comment by chotaire** [comment] 2019-07-31 20:59
Due to a storm of issues with other irc clients running into https://github.com/inspircd/inspircd/issues/1636#issuecomment-490224949 I had to do an emergency downgrade of the ircd before I could do more debugging. It looks like irssi also only recently fixed it (and this version is not really widely distributed yet), in HexChat its only in git version yet, many mIRC users running outdated versions are affected, znc is having minor remaining issues even in the latest version as well. All android irc clients except of Revolution-IRC are affected and I have no idea if there is even an IRC v3.2 capable client left for IOS or OSX.

I will have to clone this server to set up a test instance and upgrade to inspircd v3.2 again, unfortunately that is nothing I can do tonight, it will have to wait a bit. To my knowledge, testnet.inspircd.org is also running v3 so it could be used for reproducing issues as well. After a long discussion with inspircd devs there is no way this will be reverted or could be fixed server-side in the v3 branch. Other ircds will follow, so we have to indeed take a look into this. I'll be back once I have the time to set up a test environment, sorry for the wait.

**Comment by lrstanley** [comment] 2019-08-01 03:48
Wasn't able to replicate on their testnet. Issues mentioned in https://github.com/inspircd/inspircd/issues/1636#issuecomment-490224949 are unrelated (at least, with the latest version of girc, see https://github.com/lrstanley/girc/commit/51b8e096d398e4c5991dcbc073988218d4e94751). However, I believe I did fix a bug in girc, I have no idea if it will fix the issues with inspircd though.

Specifically, events that have tags but no source:

```

**Comment by 42wim** [comment] 2019-09-05 21:50
@chotaire can you try https://bintray.com/42wim/nightly/Matterbridge/v1.15.1-9-g82040f5#files ?
This build has updated girc library.
Let me know if it's still an issue, thanks!

**Comment by chotaire** [comment] 2019-09-05 23:37
Awesome, I'll update matterbridge now but it will take days if not weeks until I can actually re-test with inspircd 3.x. There were too many issues with other clients too. Will set up a test network for this when I get back from vacation.

**Comment by 42wim** [comment] 2019-09-06 18:49
@chotaire no problem, I'm going to close this issue for now though as @lrstanley can't reproduce it on the girc version that matterbridge will be running from now on.

If you still experience the issue in the future, feel free to reopen.

**Closed by 42wim** 2019-09-06 18:49 UTC
Labels: waiting for feedback
