### ISSUE TITLE
Messages are getting duplicatet over ssh-chat gateway

### ISSUE THREAD

**Issue by thefeiter** [42wim/matterbridge#950] opened 2019-11-18 11:12 UTC
When I bridge for example SSH-chat nd Matrix and send a Message to the matrix room, it gets relayed to ssh-chat. But then the Bridge re-relays the message sent to ssh-chat to matrix again

My gateway config:

[sshchat.chat]
Server="xxxx.de:2222"
Nick="matterbridge"
RemoteNickFormat="[{PROTOCOL}] @{NICK}: "

[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="matrix.mymatrix"
channel="#xxx:xxx.de"

[[gateway.inout]]
account="sshchat.chat"
channel="sshchat"

Is there anything I can do to suppress this duplification?

**Comment by 42wim** [comment] 2019-12-07 21:01
What matterbridge version? Can't reproduce this on latest release.
Please paste the debug logs.

**Comment by thefeiter** [comment] 2019-12-08 21:37
Shure, how can I enable debug mode in docker-compose?

**Comment by thefeiter** [comment] 2019-12-08 21:58
sending "p" in matrix

`

[0019] DEBUG matrix:       == Receiving event: &gomatrix.Event{StateKey:(*string)(nil), Sender:"@thefeiter:mydomain.de", Type:"m.room.message", Timestamp:1575841897742, ID:"$G5WlVVLNwfcgFToP7w19aFReqAyhs9FHNBl7D6OQFvE", RoomID:"!asijszsmDYgjfwfrWi:mydomain.de", Content:map[string]interface {}{"body":"p", "msgtype":"m.text"}, Redacts:"", Unsigned:map[string]interface {}{"age":148}}
[0019] DEBUG matrix:       Unknown room !asijszsmDYgjfwfrWi:mydomain.de
[0019] DEBUG matrix:       == Receiving event: &gomatrix.Event{StateKey:(*string)(nil), Sender:"@thefeiter:mydomain.de", Type:"m.room.message", Timestamp:1575841897742, ID:"$G5WlVVLNwfcgFToP7w19aFReqAyhs9FHNBl7D6OQFvE", RoomID:"!asijszsmDYgjfwfrWi:mydomain.de", Content:map[string]interface {}{"body":"p", "msgtype":"m.text"}, Redacts:"", Unsigned:map[string]interface {}{"age":150}}
[0019] DEBUG matrix:       <= Sending message from @thefeiter:mydomain.de on matrix.mymatrix to gateway
[0019] DEBUG gateway:      => Sending config.Message{Text:"p", Channel:"#botbastler:mydomain.de", Username:"thefeiter", UserID:"@thefeiter:mydomain.de", Avatar:"", Account:"matrix.mymatrix", Event:"", Protocol:"", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xbf7379fa8c6b0cf2, ext:19662414829, loc:(*time.Location)(0x558f68ba3fc0)}, ID:"$G5WlVVLNwfcgFToP7w19aFReqAyhs9FHNBl7D6OQFvE", Extra:map[string][]interface {}(nil)} from matrix.mymatrix (#botbastler:mydomain.de) to sshchat.chat (sshchat)
[0019] DEBUG sshchat:      => Receiving config.Message{Text:"p", Channel:"sshchat", Username:"[matrix] @thefeiter: ", UserID:"@thefeiter:mydomain.de", Avatar:"", Account:"matrix.mymatrix", Event:"", Protocol:"", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xbf7379fa8c6b0cf2, ext:19662414829, loc:(*time.Location)(0x558f68ba3fc0)}, ID:"", Extra:map[string][]interface {}(nil)}
[0019] DEBUG sshchat:      <= Message []string{"[matterbridge2] [matrix] @thefeiter", " p\r"}
[0019] DEBUG gateway:      => Sending config.Message{Text:"p", Channel:"sshchat", Username:"[matterbridge2] [matrix] @thefeiter", UserID:"nick", Avatar:"", Account:"sshchat.chat", Event:"", Protocol:"", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xbf7379fa8cb4f620, ext:19667258674, loc:(*time.Location)(0x558f68ba3fc0)}, ID:"", Extra:map[string][]interface {}(nil)} from sshchat.chat (sshchat) to matrix.mymatrix (#botbastler:mydomain.de)
[0019] DEBUG matrix:       => Receiving config.Message{Text:"p", Channel:"#botbastler:mydomain.de", Username:"[sshchat] <[matterbridge2] [matrix] @thefeiter> ", UserID:"nick", Avatar:"", Account:"sshchat.chat", Event:"", Protocol:"", Gateway:"gateway1", ParentID:"", Timestamp:time.Time{wall:0xbf7379fa8cb4f620, ext:19667258674, loc:(*time.Location)(0x558f68ba3fc0)}, ID:"", Extra:map[string][]interface {}(nil)}
[0019] DEBUG matrix:       Channel #botbastler:mydomain.de maps to channel id !asijszsmDYgjfwfrWi:mydomain.de
[0019] DEBUG gateway:      mID matrix.mymatrix: $kxtfkbWWi1-DK5UN8ytDmZh9MNb0AEo1HzRlQkhbkq8
[0019] DEBUG matrix:       == Receiving event: &gomatrix.Event{StateKey:(*string)(nil), Sender:"@matterbridge:mydomain.de", Type:"m.room.message", Timestamp:1575841898275, ID:"$kxtfkbWWi1-DK5UN8ytDmZh9MNb0AEo1HzRlQkhbkq8", RoomID:"!asijszsmDYgjfwfrWi:mydomain.de", Content:map[string]interface {}{"body":"[sshchat] <[matterbridge2] [matrix] @thefeiter> p", "format":"org.matrix.custom.html", "formatted_body":"[sshchat] &lt;[matterbridge2] [matrix] @thefeiter&gt; p", "msgtype":"m.text"}, Redacts:"", Unsigned:map[string]interface {}{"age":88}}
[0019] DEBUG matrix:       == Receiving event: &gomatrix.Event{StateKey:(*string)(nil), Sender:"@matterbridge:mydomain.de", Type:"m.room.message", Timestamp:1575841898275, ID:"$kxtfkbWWi1-DK5UN8ytDmZh9MNb0AEo1HzRlQkhbkq8", RoomID:"!asijszsmDYgjfwfrWi:mydomain.de", Content:map[string]interface {}{"body":"[sshchat] <[matterbridge2] [matrix] @thefeiter> p", "format":"org.matrix.custom.html", "formatted_body":"[sshchat] &lt;[matterbridge2] [matrix] @thefeiter&gt; p", "msgtype":"m.text"}, Redacts:"", Unsigned:map[string]interface {}{"age":82, "transaction_id":"go1575841898215070376"}}`

**Comment by 42wim** [comment] 2019-12-08 21:59
What matterbridge version and what ssh-chat version?

**Comment by thefeiter** [comment] 2019-12-08 22:03
Debug log of sending "p" to matrix room.
[debuglog.txt](https://github.com/42wim/matterbridge/files/3937225/debuglog.txt)

**Comment by 42wim** [comment] 2020-02-02 21:08
Thanks for the feedback, fixed in master now.

**Closed** 2020-02-02 21:08 UTC
Labels: bug
