### ISSUE TITLE
Support edits on Gitter

### ISSUE THREAD

**Issue by jleclanche** [42wim/matterbridge#238] opened 2017-08-11 08:32 UTC
Gateway config:  <> Discord <-> Gitter <-> IRC <>.

When posting a message on Discord, then editing it, the bot will post a new message on IRC and Gitter instead of modifying it. This behaviour is OK on IRC, but Gitter has the ability to edit a message; it'd be nice to get that supported!

**Comment by 42wim** [comment] 2017-08-27 22:47
duplicate of #223 (I'm working on supporting it)

**Closed by 42wim** 2017-08-27 22:47 UTC
Labels: enhancement
