### ISSUE TITLE
Unable to connect to inspircd after 1.4.0 switch to girc

### ISSUE THREAD

**Issue by haam3r** [42wim/matterbridge#485] opened 2018-08-22 05:28 UTC
**Describe the bug**
Any release from 1.4.0 up is unable to connect to a local inspircd server.
Seems that switching to girc is causing the problem.
Connects successfully with version 1.3.1 of matterbridge 

**To Reproduce**
Matterbridge ver 1.4.0 and up with Inspircd 2.0.24
When connecting to Inspircd matterbridge errors out on a registration timeout

**Expected behavior**
Matterbridge connects to the IRC server and establishes a bridge between certain channels there and in mattermost.

**Screenshots/debug logs**
[0000]  INFO irc:          Connecting inspircd.server.local:port
[0000] DEBUG irc:          "CLIENT_INIT :inspircd.server.local:port"
[0000] DEBUG irc:          ":inspircd.server.local NOTICE Auth :*** Looking up your hostname..."
[0000] DEBUG irc:          ":inspircd.server.local CAP 287AAAJTO LS :"
[0006] DEBUG irc:          ":inspircd.server.local NOTICE Auth :*** Could not resolve your hostname: Request timed out; using your IP address (<matter server IP>) instead."
[0010] DEBUG irc:          "ERROR :Closing link: (mbridge@<matter server IP>) [Registration timeout]"
[0010] ERROR irc:          disconnect: error: EOF
[0010]  INFO irc:          reconnecting in 30 seconds...
[0030] FATAL main:         Starting gateway failed: Bridge irc.sirts failed to start: connection timed out

**Environment (please complete the following information):**
 - OS: [e.g. linux] Ubuntu 16.04 LTS
 - Matterbridge version: `version: 1.11.1 c4c6aff`

**Additional context**
Matterbridge:
```
[irc]
    [irc.sirts]
    Server="inspircd.server.local:port"
    Nick="mbridge"
    UseTLS=true
    SkipTLSVerify=true
    PrefixMessagesWithNick=true
    ShowJoinPart=true
    RemoteNickFormat="<{NICK}> "
    Password="*********************"
```

Inspircd server:
```
<connect
        allow="<matter server IP>"
        maxchans="30"
        timeout="10"
#        password="*************"
        pingfreq="120"
        recvq="8192"
        localmax="15"
        globalmax="15"
        useident="no"
        limit="5000"
        modes="+x"
        port="****">
```

**Comment by 42wim** [comment] 2018-08-26 22:13
I've just tested against irc.inspircd.org and matterbridge could connect correctly.
It shows different caps than yours, shouldn't `CAP` also show `tls` on your inspircd when you use TLS connections ?
```
[0011] DEBUG irc:          ":zoidberg.chatspike.net CAP 598AAEYD2 LS :multi-prefix sasl tls userhost-in-names"
[0011] DEBUG irc:          ":zoidberg.chatspike.net CAP mattxxx ACK :multi-prefix userhost-in-names"
```

**Comment by haam3r** [comment] 2018-09-03 14:08
That's a good hint.
Seems that because our server uses openssl and not gnutls, the CAP LS command does not send the tls option, because starttls requires the m_ssl_gnutls.so module (https://wiki.inspircd.org/STARTTLS_Documentation).

My guess is that girc expects the starttls capability instead of just initiating a TLS connection and sending a normal PASS/USER/NICK?

Funny thing here, as per the doc of inspircd: `It is important to note that if m_cap is not loaded on an InspIRCd server, or a server does not support CAP at all, then CAP LS will generate no output. The client author must send the normal PASS/USER/NICK immediately following the CAP LS command to handle this case.`
This would suggest that my inspircd server does not have CAP module loaded since the CAP LS command returns empty output, but doing /modules on the server shows: `702 m_cap.so Client CAP extension support` which would indicate that CAP is indeed loaded.

I guess this means that to make newer versions of matterbridge work, I'm going to have to switch the inspircd server over to using GnuTLS?

**Comment by 42wim** [comment] 2018-09-13 21:50
I don't think the problem is TLS, because otherwise you shouldn't have the debug logs.
Looking at the girc code, it does TLS handshake when tls=true is specified.

I think the issue is that girc doesn't send a `CAP END` when the `CAP LS` is empty.
In the `handlecap` function at https://github.com/lrstanley/girc/blob/master/cap.go#L90

The best thing is to open an issue at https://github.com/lrstanley/girc/issues/new and reference this issue.

**Comment by lrstanley** [comment] 2018-09-13 22:11
Was able to replicate by forcing the `CAP LS` message to be empty. Fix is in https://github.com/lrstanley/girc/commit/0fb5b684054ebfa2f3fe6306c3161dc637e9b7c6.

**Comment by 42wim** [comment] 2018-09-13 22:30
@haam3r you can find a dev binary with this fix on https://bintray.com/42wim/nightly/Matterbridge/v1.11.3-4-ge0ca876#files

@lrstanley thanks! 👍

**Comment by haam3r** [comment] 2018-09-17 06:06
Fix worked. I am able to succesfully bridge, messages are being relayed.
@lrstanley & @42wim Thanks a lot
Will the fix be merged into the next stable release as well?

**Comment by 42wim** [comment] 2018-09-17 10:50
Good to hear it's working.
Yes, it'll be in next stable too.

**Closed by 42wim** 2018-09-17 10:50 UTC
Labels: waiting for feedback
