### ISSUE TITLE
Possible to pick up XMPP messages sent to a specific user and post to Mattermost?

### ISSUE THREAD

**Issue by rupertd** [42wim/matterbridge#84] opened 2016-11-18 16:53 UTC
I have successfully integrated XMPP jabber into mattermost 3.5.  Conversations in a MUC room in XMPP are being gatewayed into the relevant channel in mattermost.  So, the normal and expected behaviour there is working as intended for routine chats in a conference room.

A scenario we face a lot with our XMPP environment is that 'broadcasts' are sent to ALL users on the XMPP service via an extension to it as a 'broadcast service'; which I'd also like to relay to the mattermost channel via the integration.  I can see that the broadcast xmpp messages are being received by the Gateway. Here's a recent example;

``<message to="xxxx@xxx.com/xxx" type="chat" xml:lang="en" from="xxx@xx.com/xxxx"><body>Please don't forget to update your packs - there are new items added with the Update/Patch
This was a web broadcast from xxxxx to xxxxx at xxx </body></message>``

It would be really neat if all communications that are VALID for a XMPP user are capable of being gatewayed into Mattermost.  Not too sure that I've explained the scenario that well; but I gave it a try. Would it be possible to screen for all messages to xxxx@xxx.com/xxx by Jid so that those are parsed and presented via the Gateway?

We rarely use the XMPP service for user Direct Messages; more just as a listening service to receive these broadcasts over. For a large group of us its a very fast end easy way of receiving targeted information and it would be incredible to gateway these broadcasts through into Mattermost too.

**Comment by rupertd** [comment] 2016-11-18 17:13
Just thinking about this a little more; an even cooler thing would be to limit the TO and FROM scope so messages from user Y to user X can be gateway'd but all others 'ignored'.  This would allow the gateway to react only to VALID broadcasts and ignore the 'chatter'.  You can see its really only the broadcasts that I'm interested in putting through the gateway.

**Comment by 42wim** [comment] 2016-11-20 17:17
The broadcast messages are direct messages though ? 
There's no way to know if it's a broadcast message or a direct message (or is there?:)

**Comment by rupertd** [comment] 2016-11-21 07:54
Well, in the example I posted the gateway receives the 'broadcast' as a `<message to=`
Line 102 of xmpp.go tests for `if v.Type == "groupchat" {`
Could it not be as simple as `if v.Type == "message" {` ?

**Comment by 42wim** [comment] 2016-11-21 08:35
The problem  is that there is no difference between a direct (or  private) and a broadcast message. 

The difference between a public chat or a direct/private/broadcast is clear, that's not the issue. 

To allow broadcast means to allow relaying direct/private messages. Not everyone will want that. (will need to have some config to allow specific senders). 

And yes, it'll be probably as easy to pick up type=chat to allow this :)

**Comment by rupertd** [comment] 2016-11-21 08:38
That would be incredible. I have zero go experience and wouldn't have a clue how to amend/compile/build.
As indicated I have zero concerns with DM's/Private Messages as we don't use them on the xmpp service.

I note as well, although probably shouldn't in this thread that the gateway stops working after about 5 minutes of being idle.  Status updates (away, available etc) stop updating.  Is there someway to keep-alive as it seems like the heart-beat is too slow to keep the connection alive?

**Comment by 42wim** [comment] 2016-11-26 14:12
@rupertd the keepalive issue should be fixed now, could you try latest master ?

**Comment by rupertd** [comment] 2016-11-26 15:52
I will give it a try. Thanks a million.

**Comment by rupertd** [comment] 2016-11-26 16:33
Confirmed; time-out not occurring now. Awesome. Many thanks.

**Comment by 42wim** [comment] 2016-11-26 16:43
Thamks for testing and reporting back :)

**Comment by rupertd** [comment] 2016-11-26 17:00
Given I had to unnewbie myself with GO in order to run the latest master I also tried changing the XMPP.go to listen for CHAT instead of GROUPCHAT.

The expected behaviour for message type="groupchat" to no longer work did occur.
The expected behaviour for message type="chat" also did not work.

Here's the trace (with sensitive stuff removed)....

`
<message type="groupchat" id="purplexxxx" to="xxx@xxx.xxx/xxxxxhf4" from="xxx@xxx.xxx.com/xxx_xxx"><body>Test from jabber</body></message>

<message type="chat" id="xxxxxx1bb" to="xxxxx@xxxx.com/xxxxxx" from="xxx_xxx@xxx.com/5xe4xxxxx"><active xmlns="http://jabber.org/protocol/chatstates"/><body>Test from jabber as DM</body></message>
`
My method was to CD into the /github.com/42wim/matterbridge from your latest master, change xmpp.go to read if v.Type == "chat" { on line 112) then I used GO RUN MATTERBRIDGE.GO with a working matterbridge.toml . The matterbridge ran fine but neither CHAT or GROUPCHAT messages make it into mattermost.

One step forwards!  Must be something I was doing wrong in trying to run the GO application?  At least we proved that your new MASTER deals with the xmpp timeout issue.  Many thanks for that!

**Comment by 42wim** [comment] 2017-11-24 22:07
basically duplicate of #191

**Closed by 42wim** 2017-11-24 22:07 UTC
Labels: maybe
