### ISSUE TITLE
Completely disable threading from slack to discord and vice versa. Not include threaded replies at all.

### ISSUE THREAD

**Issue by shoeplexben** [42wim/matterbridge#1519] opened 2021-06-15 23:15 UTC
Opened an issue before but was directed to the preserve threading setting, I have preservethreading set to false, but it still reposts the thread replies from slack to discord and vice versa.. 

is there any feature to completely disable replies in threads on slack from transferring to discord?

**Comment by qaisjp** [comment] 2021-06-16 13:50
Duplicate of #1479

**Closed by qaisjp** 2021-06-16 13:50 UTC
Labels: enhancement
