### ISSUE TITLE
Reason for dedicated Slack user

### ISSUE THREAD

**Issue by iojw** [42wim/matterbridge#220] opened 2017-07-17 12:03 UTC
I would like to ask if there's any particular reason why it's stated that a dedicated user (and not a bot user) should be created to use matterbridge with Slack (https://github.com/42wim/matterbridge/wiki/Slack-bot-setup). I have tested it and I'm currently using matterbridge with a Slack bot user API token (https://api.slack.com/bot-users) with no issues at all. As stated here https://api.slack.com/custom-integrations/legacy-tokens, test tokens should also ideally not be used in applications. It's also much more troublesome to create a new Slack user as compared to setting up a bot integration.

Just trying to help you improve on the documentation 🙂

**Comment by 42wim** [comment] 2017-07-18 21:10
@iojw thanks for your input

The bot user can indeed be used, but you need to invite it first, it can't join channels.
I didn't want to confuse users with multiple options, even with single options they still have issues ;-)
(and also lack of time for writing extra documentation)

Please feel free to add a new page to the wiki describing this setup, it would be much appreciated!
Or modify other pages to make them more clear.

**Comment by iojw** [comment] 2017-07-21 06:16
Ah totally get you there 🙂. I'll help you edit the wiki the include this soon!

**Comment by retiform** [comment] 2017-07-27 04:13
I read this after setting up the user account...

**Comment by jheiselman** [comment] 2017-08-02 19:44
Just found an issue with using a bot account. In handleSlackClient during the handling of the IncomingEvents loop, the logic makes a call to GetBotInfo (slack.go:293) that in turn makes a call to the bots.info resource on the Slack servers. This method can only be called by a non-bot user though and so it returns an error and the entire message event is skipped over resulting in messages not being sent over the bridge.

**Comment by 42wim** [comment] 2017-08-02 20:43
@jheiselman aha, thanks for reporting, so with a bot account we can't relay other bots.

**Comment by jheiselman** [comment] 2017-08-02 20:52
@42wim I'm wondering if this call is strictly necessary. We already have the BotID that can be filled into the config.Message.UserID field. Not sure what would be considered a good value to fill in to the Username field, but it seems like this shouldn't result in the event getting dropped.

**Comment by 42wim** [comment] 2017-08-02 20:57
Yes, the problem is the username, we need a username of the bot. I don't know any other way to get it.

**Comment by jheiselman** [comment] 2017-08-02 22:00
Looking at the use case of a user executing /giphy in Slack, there is a User property on the event that is a user ID. Could use it to call into GetUserInfo and use that information. Maybe postpend to the user name a string indicating it was a bot like user.Name + " (bot)". I have no idea how that would work for other bots. 

In one of my Slack channels we have a Hangouts Bot that is bridging a particular Hangout to a channel. I will keep an eye out for those and see how those come across. It may be different because it isn't initiated by a Slack user.

**Comment by Helcaraxan** [comment] 2018-11-10 23:15
@42wim I think we can close this one with my work concluding on #510 ?

**Comment by Helcaraxan** [comment] 2018-11-10 23:45
Closing this in favour of #510.

**Closed by Helcaraxan** 2018-11-10 23:45 UTC
