### ISSUE TITLE
How can I relay private chat messages of XMPP

### ISSUE THREAD

**Issue by TheColdVoid** [42wim/matterbridge#1601] opened 2021-10-04 17:02 UTC
Excuse me, I have a question to ask. How can I relay private chat messages instead of channel messages to other platforms? I noticed that only channel is available in xmpp's gateway option, and I can't specify to forward a private chat sent to me by a specific user to other platforms.
How can I configure it to make private chat forwarding work? Looking forward to your reply.

**Comment by Mikaela** [comment] 2021-10-05 06:50
I fear this is currently unsupported (outside of Matrix where everything is a room) and thus a duplicate of https://github.com/42wim/matterbridge/issues/191.

**Closed** 2021-10-17 13:59 UTC
