### ISSUE TITLE
Slack upload links need a space separator

### ISSUE THREAD

**Issue by Jaykul** [42wim/matterbridge#461] opened 2018-06-29 06:12 UTC
One problem we have on our bridge is that when someone uploads an image on the slack side, it's obviously not visible on the discord side. However, this is exacerbated if they don't "comment" when posting, because the two URLs for the image (the file share and the "download" link) get stuck together and end up being rendered by discord as a single URL (which doesn't work). 

See screenshot:
![image](https://user-images.githubusercontent.com/192942/42075891-fc0be940-7b40-11e8-80bf-1e4ac966b851.png)

In the second attempt I just commented "comment" as I was uploading the image on the slack side, and the URLs get separated and are clickable.

Obviously, in an ideal world, you'd download the image and re-upload it to discord if it was small enough... but I know that's been discussed before. All I'm asking is: can we just insert a space before the second URL (regardless of whether there's a comment or not, it needs a space **before** the download url).

**Comment by 42wim** [comment] 2018-06-29 20:13
I guess you're using webhooks ? because if you use token and not the webhooks, images from slack will be downloaded and uploaded to discord.

**Comment by 42wim** [comment] 2018-06-29 20:35
Fixed in master now, thanks for reporting!

**Closed** 2018-06-29 20:35 UTC
Labels: bug

**Comment by Jaykul** [comment] 2018-07-03 04:39
Hmm. Is there any downside to using the token method? I'm sure I had it working that way originally and switched for a reason.

**Comment by 42wim** [comment] 2018-07-03 20:38
If you have both, it should just upload the images, also a bug maybe.
If you can reproduce, please open an issue with your config.

**Comment by Jaykul** [comment] 2018-07-03 21:10
Ok, good to know. I know that it *was* uploading images at one point (unless they were too large). I will double-check the token is still valid when I get home this evening.
