### ISSUE TITLE
autobridge based on rooms invited to

### ISSUE THREAD

**Issue by hramrach** [42wim/matterbridge#893] opened 2019-09-12 19:29 UTC
**Is your feature request related to a problem? Please describe.**
Configuring channels in a central configuration file is annoying and scales poorly with users creating their own rooms. The server already stores channel membership for protocols like mattermost or rocketchat anyway so there is no need to duplicate a channel list in configuration file.

**Describe the solution you'd like**
The bot can just bridge any room it is invited in to same named room on other protocols.

**Comment by 42wim** [comment] 2019-09-14 21:06
duplicate of #42

**Closed by 42wim** 2019-09-14 21:06 UTC
