### ISSUE TITLE
XMPP/Mattermost sync

### ISSUE THREAD

**Issue by v1r** [42wim/matterbridge#867] opened 2019-07-31 17:24 UTC
Hi there,
Hope you are doing well!

I am trying to bridge XMPP with Mattermost and I have a few questions:
~~- Does the bridge is intended to sync direct/private messages.. Let's say I wrote a durect message to xxx@jabber from a jabber client.. Does the message will be sent to that user in Mattermost?~~

After readign this https://github.com/42wim/matterbridge/issues/84, is there any fork of the repose that can enable direct messages? 

~~- Also I am able to get a working config but there is messages are being relayed to both sides.. and I am not sure what to put in the channel attribute of the XMPP gateway config..~~ [Resolved]

**Edit:**
I just started reading this thread:
https://github.com/42wim/matterbridge/issues/84

The following is my configuration and output:

```
[xmpp.jabber]
Server="xxx:5222"
Jid="xxx"
Password="xxx"
Nick="xxx"
Muc="xxx@conference."
NoTLS=true
SkipTLSVerify=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "


[mattermost.mymattermost]
#The mattermost hostname. (do not prefix it with http or https)
Server="xxxx"
SkipVersionCheck=true
Team="xxxx"
Nick="xxxx"
Login="xxx"
Password="xxxx"
NoTLS=true
RemoteNickFormat="[{PROTOCOL}] <{NICK}> "
PrefixMessagesWithNick=true


[[gateway]]
name="gateway1"
enable=true

[[gateway.inout]]
account="mattermost.mymattermost"
channel="town-square"

[[gateway.inout]]
account="xmpp.jabber"
channel="NOT SURE WHAT TO PUT HERE"
```
Output: 

```
[2019-07-31T17:02:36Z]  INFO main:         Running version 1.15.2-dev 79a006c
[2019-07-31T17:02:36Z]  INFO main:         WARNING: THIS IS A DEVELOPMENT VERSION. Things may break.
[2019-07-31T17:02:36Z]  INFO router:       Parsing gateway gateway1
[2019-07-31T17:02:36Z]  INFO router:       Starting bridge: xmpp.jabber
[2019-07-31T17:02:36Z]  INFO xmpp:         Connecting xxx::5222
[2019-07-31T17:02:36Z]  INFO xmpp:         Connection succeeded
[2019-07-31T17:02:36Z]  INFO xmpp:         xmpp.jabber: joining xxx@conference(ID: test@conference.xxx xmpp.jabber)
[2019-07-31T17:02:36Z]  INFO router:       Starting bridge: mattermost.mymattermost
[2019-07-31T17:02:36Z]  INFO mattermost:   Connecting using login/password (sending and receiving)
[2019-07-31T17:02:36Z]  INFO mattermost:   Connecting xxxx@xxx (team: xxx) on 192.8.202.241:8000
[0000]  INFO matterclient: found 8 users in team town-square
[2019-07-31T17:02:37Z]  INFO mattermost:   Connection succeeded
[2019-07-31T17:02:37Z]  INFO mattermost:   mattermost.mymattermost: joining town-square (ID: town-squaremattermost.mymattermost)
[2019-07-31T17:02:37Z]  INFO main:         Gateway(s) started succesfully. Now relaying messages

```

Thanks for illuminating me!

**Comment by 42wim** [comment] 2019-07-31 20:30
Hi, no sorry, direct messages to users isn't possible yet.
Only public channels.

**Comment by v1r** [comment] 2019-07-31 23:28
@42wim Thanks for you quick answer. Do you think it will be available in the near future? I would also be surprise if is faisable.. I mean direct messages are meant to be private... How it can be possible to catch or intercept that via a gateway... I am not so familiar with XMPP so it may be a dump question that I am asking :).

**Comment by poVoq** [comment] 2019-08-29 19:30
You could set up MatterIRCd and Biboumi (a XMPP to IRC gateway) to have a per user connection.

**Comment by 42wim** [comment] 2019-09-05 21:42
Duplicate of #191

**Closed by 42wim** 2019-09-05 21:42 UTC
