### ISSUE TITLE
RocketChat -> Matrix images are considered empty text

### ISSUE THREAD

**Issue by anadahz** [42wim/matterbridge#998] opened 2020-02-03 15:01 UTC
**Environment (please complete the following information):**
 - OS: Linux (Docker)
 - Matterbridge Docker image: 42wim/matterbridge:1.16.3

**Describe the bug**
RocketChat bridge defines the image message as empty text `Text:""`. 
The gateway discards the empty message:

**Debug logs excerpt**
```
Rocketchat:   <= Message is &config.Message{Text:"", Channel:"#channel", [..]
Gateway:  ignoring empty message &config.Message{Text:"", Channel:"#channel", [..]
```

**To Reproduce**
Send an image in RocketChat.

**Expected behavior**
RocketChat should transmit the image to Matrix.

**Comment by 42wim** [comment] 2020-02-08 17:58
duplicate of #774

**Closed by 42wim** 2020-02-08 17:58 UTC

**Comment by qaisjp** [comment] 2020-02-08 19:47
Duplicate of #774
