### ISSUE TITLE
Matrix->Discord: Pasted imgs show up as "attachments" or don't send at all

### ISSUE THREAD

**Issue by Nobabs27** [42wim/matterbridge#331] opened 2018-01-08 04:06 UTC
If you send an image using the "Upload file" button on Riot it sends just fine.
But if you were to copy and image (say from a browser, Right Click->Copy Image) and paste it, it show up as an "Attachment" in Discord rather than an image.

On Matrix/Riot (you can see two images, the first one upload the second one pasted):
![screenshot_2018-01-07_23-00-22](https://user-images.githubusercontent.com/15079776/34658633-a241322c-f3fe-11e7-8ffb-a12b68845421.png)
On Discord (the uploaded one shows, but the other one shows only as "attachment"):
![screenshot_2018-01-07_23-00-36](https://user-images.githubusercontent.com/15079776/34658639-a76d22ba-f3fe-11e7-9472-ec0873662ba0.png)

Using the latest 1.7.0-dev version of matterbridge.
Not sure if this is present when bridging Matrix with other things.

**Comment by 42wim** [comment] 2018-01-09 22:45
What browser do you use ? 
Works fine when I test with chrome, chrome tries to upload it as image.png, your browser tries to upload it as "attachment" without an extension

**Comment by Nobabs27** [comment] 2018-01-10 05:31
Using riot-desktop and just regular Discord (not the web version).
For the browser I am copying it from, I have tested:
Falkon (pastes as "Attachment")
Chromium (pastes as "Attachment")
Brave (pastes a link)
Waterfox (pastes as "Attachment")

Now it seems to be not even sending "Attachment" discord side, just nothing what-so-ever.

**Comment by 42wim** [comment] 2018-01-10 22:39
Can not reproduce this, are you on windows ?
Could you try with a "mainstream" browser ?

**Comment by Nobabs27** [comment] 2018-01-12 23:22
On Manjaro Linux, xmonad.
Chromium is basically Chrome but I'll try Firefox and Chrome as well.

**Comment by Nobabs27** [comment] 2018-01-14 21:13
Well, now they seem to be not sending at all (not even as "attachments").
I am pressing Ctrl+V to paste.

Did a screen recording of the issue this time, copying from both Google Chrome and Mozilla Firefox:
https://youtu.be/tWfnsAqE8_c

**Comment by 42wim** [comment] 2018-01-14 21:55
Saw the video, the attachments are 3.17MB, only 1MB size gets uploaded. (your previous attachments were much smaller)

See https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample#L1051-L1059 for a config option.

So please add that option to increase filesize, or do smaller images :-)

Then restart matterbridge with `-debug` option and do the same again, paste screenshot in matrix.
Then paste the debug output here or on pastebin.com

The issue is probably because the linux browser don't send an extension they just do `attachment`. Windows names the files `image.png` or `image.jpg`, but the `-debug` output will help me to fix it.

**Comment by 42wim** [comment] 2018-01-20 17:26
@Nobabs27 could you try the latest devel build ?
https://bintray.com/42wim/nightly/Matterbridge/v1.6.0-21-g7119e37#files
It should be fixed now

**Comment by Nobabs27** [comment] 2018-01-23 21:29
The bin from that link didn't work for me...
It works on my C2D desktop, but not my Xeon server computer.

Anyway, so I tried running it on my desktop and it does send the image correctly. :+1:

**Comment by 42wim** [comment] 2018-01-23 21:32
:tada:

**Closed by 42wim** 2018-01-23 21:32 UTC
Labels: waiting for feedback
