### ISSUE TITLE
Matterbridge still sometimes doesn't reconnect to IRC

### ISSUE THREAD

**Issue by jleclanche** [42wim/matterbridge#259] opened 2017-09-14 17:30 UTC
I don't know if it's specifically after disconnects, netsplits or anything like that but sometimes on Freenode, I get `⇐ +TardisBot quit (~TardisBot@HearthSim/Bot/TardisBot) Read error: Connection reset by peer` and it never reconnects. I have to restart matterbridge to get it to reconnect.

This used to be much worse but I remember @42wim implemented some auto-reconnect, it doesn't look like it's foolproof though.

**Comment by 42wim** [comment] 2017-09-14 17:41
do you use sasl?

**Comment by jleclanche** [comment] 2017-09-14 17:54
Yep

**Comment by 42wim** [comment] 2017-09-18 22:05
I noticed those too, kinda hard to reproduce though (and caused by the irc lib i'm using).

**Comment by 42wim** [comment] 2017-09-25 18:37
I'm reproducing connection resets, but the bot eventually always manage to reconnect.

If it happens again could you paste your logs of the disconnect and reconnects ?
Even when not running debug they should show something like this
```
2017/09/25 20:31:27 Error, disconnected: dial tcp 81.18.73.123:6667: getsockopt: connection reset by peer
2017/09/25 20:31:27 Connected to 81.18.73.123:6667 (81.18.73.123:6667)
2017/09/25 20:31:27 Error, disconnected: write tcp 10.112.79.42:46966->81.18.73.123:6667: write: connection reset by peer
2017/09/25 20:31:27 Connected to 81.18.73.123:6667 (81.18.73.123:6667)
2017/09/25 20:31:27 Error, disconnected: read tcp 10.112.79.42:46968->81.18.73.123:6667: read: connection reset by peer
2017/09/25 20:31:27 Connected to 81.18.73.123:6667 (81.18.73.123:6667)
2017/09/25 20:31:27 Error, disconnected: read tcp 10.112.79.42:46970->81.18.73.123:6667: read: connection reset by peer
2017/09/25 20:31:27 Connected to 81.18.73.123:6667 (81.18.73.123:6667)
2017/09/25 20:31:27 Error, disconnected: read tcp 10.112.79.42:46972->81.18.73.123:6667: read: connection reset by peer
2017/09/25 20:31:27 Connected to 81.18.73.123:6667 (81.18.73.123:6667)
2017/09/25 20:31:27 Error, disconnected: read tcp 10.112.79.42:46974->81.18.73.123:6667: read: connection reset by peer
2017/09/25 20:31:27 Connected to 81.18.73.123:6667 (81.18.73.123:6667)
2017/09/25 20:31:27 Error, disconnected: read tcp 10.112.79.42:46976->81.18.73.123:6667: read: connection reset by peer
2017/09/25 20:31:27 Connected to 81.18.73.123:6667 (81.18.73.123:6667)
2017/09/25 20:31:27 Error, disconnected: write tcp 10.112.79.42:46978->81.18.73.123:6667: write: connection reset by peer
2017/09/25 20:31:27 Error while reconnecting: dial tcp 81.18.73.123:6667: getsockopt: connection reset by peer
```

**Comment by lrstanley** [comment] 2017-10-19 20:14
I was about to write a discord<->irc relay bot today for a friend as they were getting tired of the node-based relay bots, however I noticed this tool linked in discordgo's readme so I checked it out. Saw this in the issues, and wanted to give you a heads up on a few things. I used to use the **go-ircevent** library, till I noticed all sorts of odd and one-off issues, which I ended up writing my own library. Looking through `bridge/irc/irc.go` alone, I'm noticing that most of the things you have implemented, are implemented in my library (full user/nick tracking, mainly). I still need to clean up/add a few more tests, and tag the first 1.0.0 release. I've been using it in a few github-released projects, and quite a few more private bots for various things. I suggest checking it out -- it's higher level than go-ircevent, but I think you may find it extremely useful. :+1: https://github.com/lrstanley/girc

https://godoc.org/github.com/lrstanley/girc#ex-package--Simple for an example of how you'd complete reconnect logic.

**Comment by 42wim** [comment] 2017-10-19 21:35
@lrstanley Thanks for this tip, your library looks very good!
I'm definitely going to test this.

**Comment by 42wim** [comment] 2017-10-20 22:57
If anyone want to help testdrive girc they can use the girc branch https://github.com/42wim/matterbridge/tree/girc

**Comment by 42wim** [comment] 2017-11-08 22:33
v1.4.0 released with girc.
If irc problems persist, please reopen

**Closed by 42wim** 2017-11-08 22:33 UTC
Labels: bug, help wanted, library issue
