### ISSUE TITLE
Changing your nick (with /nick) on Discord crashes matterbridge

### ISSUE THREAD

**Issue by DrLynix** [42wim/matterbridge#198] opened 2017-06-15 10:47 UTC
Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```

version: 0.13.0 7811c33

### If you're having problems with mattermost please specify mattermost version. 

(Even though I don't think it's linked to Mattermost)
Version: 3.9.0
Build Number: 3.9.0
Build Date: Mon May 15 20:26:34 UTC 2017
Build Hash: ae3a62ef95e22ff67236e8addb1e4ca005307443
Build Enterprise Ready: true
DB Version: 3.9.0

### Please describe the expected behavior.

Changing my nick locally to a Discord server works and changes the nickname the bot uses to print my messages.

#### Use logs from running ```matterbridge -debug``` if possible.

Matterbridges crashes.
```
DEBU[2017-06-15T11:59:01+02:00] Receiving config.Message{Text:"Attendez je teste un truc", Channel:"discussions-1", Username:"**L\u200bynix**: ", Avatar:"https://cdn.discordapp.com/avatars/83928726282174464/81a60c13f7b603e30b49d8385ba8ba4e.jpg", Account:"discord.g42", Event:"", Protocol:"discord", Timestamp:time.Time{sec:63633117541, nsec:985269998, loc:(*time.Location)(0xdcea60)}}  module=mattermost
DEBU[2017-06-15T11:59:01+02:00] WsReceiver: model.WebSocketEvent{Event:"posted", Data:map[string]interface {}{"channel_display_name":"Discussions", "channel_name":"discussions-1", "channel_type":"O", "post":"{\"id\":\"ga1zyhg4utbq8exnsnnu4xt8na\",\"create_at\":1497520741992,\"update_at\":1497520741992,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"mcef1bgnbtghpm97t555mn1j7y\",\"channel_id\":\"nbqx4qbxmfbt9j9u3zhoq5t63w\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"**L\u200bynix**: Attendez je teste un truc\",\"type\":\"\",\"props\":{},\"hashtags\":\"\",\"pending_post_id\":\"\"}", "sender_name":"dbot", "team_id":"g1m3enn467gmfy1ki8bunjtroh"}, Broadcast:(*model.WebsocketBroadcast)(0xc4202a2a80), PreComputeJson:[]uint8(nil)}  module=matterclient
DEBU[2017-06-15T11:59:01+02:00] map[string]interface {}{"channel_display_name":"Discussions", "channel_name":"discussions-1", "channel_type":"O", "post":"{\"id\":\"ga1zyhg4utbq8exnsnnu4xt8na\",\"create_at\":1497520741992,\"update_at\":1497520741992,\"edit_at\":0,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"mcef1bgnbtghpm97t555mn1j7y\",\"channel_id\":\"nbqx4qbxmfbt9j9u3zhoq5t63w\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"**L\u200bynix**: Attendez je teste un truc\",\"type\":\"\",\"props\":{},\"hashtags\":\"\",\"pending_post_id\":\"\"}", "sender_name":"dbot", "team_id":"g1m3enn467gmfy1ki8bunjtroh"}  module=mattermost
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7ad266]

goroutine 193 [running]:
github.com/42wim/matterbridge/bridge/discord.(*bdiscord).memberUpdate(0xc4200e57a0, 0xc4201681e0, 0xc420114180)
        /go/src/github.com/42wim/matterbridge/bridge/discord/discord.go:151 +0x1e6
github.com/42wim/matterbridge/bridge/discord.(*bdiscord).(github.com/42wim/matterbridge/bridge/discord.memberUpdate)-fm(0xc4201681e0, 0xc420114180)
        /go/src/github.com/42wim/matterbridge/bridge/discord/discord.go:54 +0x3e
github.com/42wim/matterbridge/vendor/github.com/bwmarrin/discordgo.guildMemberUpdateEventHandler.Handle(0xc420197860, 0xc4201681e0, 0x9b38c0, 0xc420114180)
        /go/src/github.com/42wim/matterbridge/vendor/github.com/bwmarrin/discordgo/eventhandlers.go:368 +0x57
created by github.com/42wim/matterbridge/vendor/github.com/bwmarrin/discordgo.(*Session).handle
        /go/src/github.com/42wim/matterbridge/vendor/github.com/bwmarrin/discordgo/event.go:158 +0xc2
```

### Any steps to reproduce the behavior?

Changes your nick with /nick on Discord (not with the global nickname changes, that works).

#### (be sure to exclude or anonymize private data (tokens/passwords))

```
[discord]
    [discord.g42]
    Token="**private"
    Server="**private**"
    EditDisable=true

[mattermost]
    [mattermost.g42]
    useAPI=true
    Server="mattermost.digitalpulsesoftware.net" 
    Team="groupe-42"
    Login="**private**"
    Password="**private**"
    PrefixMessagesWithNick=true
    EditDisable=true

[general]
RemoteNickFormat="**{NOPINGNICK}**: "

[[gateway]]
    name = "Discussions"
    enable=true

    [[gateway.inout]]
    account = "discord.g42"
    channel="ID:**private**"

    [[gateway.inout]]
    account ="mattermost.g42"
    channel = "discussions-1"

[[gateway]]
    name = "Discussions 2"
    enable=true

    [[gateway.inout]]
    account = "discord.g42"
    channel="ID:**private**"

    [[gateway.inout]]
    account ="mattermost.g42"
    channel = "**private**"
```

**Comment by 42wim** [comment] 2017-06-15 11:37
Interesting, is this reproducible ? or just happened once ?

**Comment by DrLynix** [comment] 2017-06-15 12:59
Happens everytime the /nick command is used on Discord.

**Comment by 42wim** [comment] 2017-06-15 20:32
I can't reproduce it here, not on v0.13.0 and not on v0.14.0.
But I added some code to possibly avoid it. 
Could you rebuild from current master and test ?

**Comment by DrLynix** [comment] 2017-06-15 21:32
Sure, it'll be my first attempt at compiling an Go app but i'll try by following the manual. Will do that tomorrow.

**Comment by 42wim** [comment] 2017-06-15 21:35
If you're stuck feel free to ask :-)

**Comment by 42wim** [comment] 2017-06-26 21:15
I'm going to close this, v0.15.0 has been released a week ago which has this fix in it. If it still happens, feel free to reopen this.

**Closed by 42wim** 2017-06-26 21:15 UTC
Labels: waiting for feedback
