### ISSUE TITLE
Discord to slack completely broken. It's an issue for all matterbridge users.

### ISSUE THREAD

**Issue by shoeplexben** [42wim/matterbridge#1599] opened 2021-10-01 05:17 UTC
Getting this error. Slack must've pushed an api update. This is an issue for all matterbridge users that use the slack function
<img width="1374" alt="Screen Shot 2021-10-01 at 1 15 33 AM" src="https://user-images.githubusercontent.com/53308440/135569126-4cd76027-d783-44ff-97a5-5d5921651961.png">
.

**Comment by Mikaela** [comment] 2021-10-01 07:12
I think this may be a duplicate of #1598 and a problem with them instead of Matterbridge (https://github.com/42wim/matterbridge/issues/1598#issuecomment-931968935).

**Comment by qaisjp** [comment] 2021-10-03 19:54
Duplicate of #1598

**Closed by qaisjp** 2021-10-03 19:54 UTC
Labels: bug
