### ISSUE TITLE
Use IRC bot commands on another platforms

### ISSUE THREAD

**Issue by ronilaukkarinen** [42wim/matterbridge#1811] opened 2022-04-21 10:00 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to be able to for example use `!seen` command from Telegram. Right now it shows as irc as:

```
<gatewaybot> <rolle> !seen user
```

If it would be able to show it like this, it would work:

```
<gatewaybot> !seen user
```

**Describe the solution you'd like**

The could be a exception for parsing commands (that start with exclamation mark) in a format where there's no nick.

**Comment by 42wim** [comment] 2022-05-01 21:34
duplicate of #361

**Closed by 42wim** 2022-05-01 21:34 UTC
Labels: enhancement
