### ISSUE TITLE
Underscores from Discord don't arrive correctly

### ISSUE THREAD

**Issue by vpzomtrrfrt** [42wim/matterbridge#864] opened 2019-07-17 02:29 UTC
**Describe the bug**
Underscores in Discord messages don't always arrive correctly.

**To Reproduce**
- Set up a bridge from a Discord channel to another service (I tested with Matrix and IRC)
- Send a message in Discord like `_test_`
- The other rooms see what looks like a /me message, with the first underscore missing

**Expected behavior**
The message should still contain all underscores

**Screenshots/debug logs**
![image](https://user-images.githubusercontent.com/3528358/61342563-dc8d5c80-a807-11e9-880e-463f5feccd92.png)
![image](https://user-images.githubusercontent.com/3528358/61342580-e7e08800-a807-11e9-8511-cefee5a75271.png)

**Environment (please complete the following information):**
 - OS: linux
 - Matterbridge version: 1.15.1

**Additional context**

**Comment by 42wim** [comment] 2019-07-29 21:37
Thanks for reporting, seems to be a regression.
Fixed in master, you can get binaries here: https://bintray.com/42wim/nightly/Matterbridge/v1.15.1-2-gf6ad76a#files

**Closed** 2019-07-29 21:37 UTC
Labels: bug
