### ISSUE TITLE
Segfault in go-xmpp

### ISSUE THREAD

**Issue by mrexodia** [42wim/matterbridge#856] opened 2019-06-24 18:02 UTC
**Describe the bug**
I would like to prefix I know I am running a development version and I know it might not be stable, but I decided to file a bug report anyway.

At some point a user reported that the bridge died so I investigated. At first glance it looks like it fails to connect to the server, which means the service is never restarted (supervisor specific).

```
supervisor> status
matterbridge                     FATAL     Exited too quickly (process log may have details)
supervisor> tail matterbridge
> tail matterbridge
x64dbg " prefix=router
time="2019-06-19T21:18:33+02:00" level=info msg="Connecting jwchat.org" prefix=xmpp
time="2019-06-19T21:18:33+02:00" level=fatal msg="Starting gateway failed: Bridge xmpp.x64dbg failed to start: dial tcp 188.40.80.24                                                                                                       5:5222: connect: connection refused" prefix=main
time="2019-06-19T21:18:35+02:00" level=info msg="Running version 1.15.0-dev " prefix=main
time="2019-06-19T21:18:35+02:00" level=info msg="WARNING: THIS IS A DEVELOPMENT VERSION. Things may break." prefix=main
time="2019-06-19T21:18:35+02:00" level=info msg="Parsing gateway x64dbg" prefix=router
time="2019-06-19T21:18:35+02:00" level=info msg="Starting bridge: xmpp.x64dbg " prefix=router
time="2019-06-19T21:18:35+02:00" level=info msg="Connecting jwchat.org" prefix=xmpp
time="2019-06-19T21:18:35+02:00" level=fatal msg="Starting gateway failed: Bridge xmpp.x64dbg failed to start: dial tcp 188.40.80.24                                                                                                       5:5222: connect: connection refused" prefix=main
time="2019-06-19T21:18:38+02:00" level=info msg="Running version 1.15.0-dev " prefix=main
time="2019-06-19T21:18:38+02:00" level=info msg="WARNING: THIS IS A DEVELOPMENT VERSION. Things may break." prefix=main
time="2019-06-19T21:18:38+02:00" level=info msg="Parsing gateway x64dbg" prefix=router
time="2019-06-19T21:18:38+02:00" level=info msg="Starting bridge: xmpp.x64dbg " prefix=router
time="2019-06-19T21:18:38+02:00" level=info msg="Connecting jwchat.org" prefix=xmpp
time="2019-06-19T21:18:38+02:00" level=fatal msg="Starting gateway failed: Bridge xmpp.x64dbg failed to start: dial tcp 188.40.80.24                                                                                                       5:5222: connect: connection refused" prefix=main
```

I would not expect the service to actually fail to start if there are connection issues, but I can work around that now that I know.

supervisor configuration (probably not relevant, just in case):

```
[program:matterbridge]
command=/home/user/go/bin/matterbridge -conf /home/user/matterbridge/matterbridge.toml
directory=/home/user/matterbridge
autostart=true
autorestart=true
stderr_logfile=/var/log/matterbridge.err.log
stdout_logfile=/var/log/matterbridge.out.log
```

When investigating the stderror it looks like matterbridge died because it segfaulted (probably state corruption because of a bad connection/server).

It looks like the segfaul is a null pointer dereference at https://github.com/42wim/matterbridge/blob/bd0e81f5a0290fbc07a26664d327c09c306b9597/vendor/github.com/matterbridge/go-xmpp/xmpp.go#L685 and I guess this indicates that `c.Conn` is `nil`?

**To Reproduce**
Unknown, it was working great for at least 2 months. Looks like there was a connection issue (the service died, but supervisor tried restarting and couldn't connect apparently). Otherwise no reproduction steps.

**Expected behavior**
Not segfault.

**Screenshots/debug logs**
stderror:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdd040b]

goroutine 636 [running]:
github.com/42wim/matterbridge/vendor/github.com/matterbridge/go-xmpp.(*Client).Send(0x0, 0xc420892db8, 0x1c, 0x10cc928, 0x9, 0xc420542e80, 0x6, 0x0, 0x0, 0x0, ...)
        /home/user/go/src/github.com/42wim/matterbridge/vendor/github.com/matterbridge/go-xmpp/xmpp.go:685 +0x32b
github.com/42wim/matterbridge/bridge/xmpp.(*Bxmpp).handleUploadFile(0xc42044e090, 0xc4208936f0, 0x10bd0b6, 0x4, 0xc4204c5688, 0x1)
        /home/user/go/src/github.com/42wim/matterbridge/bridge/xmpp/xmpp.go:229 +0x35c
github.com/42wim/matterbridge/bridge/xmpp.(*Bxmpp).Send(0xc42044e090, 0x0, 0x0, 0xc4204e7d90, 0x6, 0xc420542e80, 0x6, 0xc420687306, 0x9, 0x0, ...)
        /home/user/go/src/github.com/42wim/matterbridge/bridge/xmpp/xmpp.go:91 +0x666
github.com/42wim/matterbridge/gateway.(*Gateway).SendMessage(0xc4204f7560, 0xc420bf8820, 0xc4204c9300, 0xc420835200, 0x0, 0x0, 0x6, 0xc4204e7d00, 0xb, 0xc4204e7d00)
        /home/user/go/src/github.com/42wim/matterbridge/gateway/gateway.go:444 +0x67b
github.com/42wim/matterbridge/gateway.(*Gateway).handleMessage(0xc4204f7560, 0xc420bf8820, 0xc4204c9300, 0x0, 0x0, 0x0)
        /home/user/go/src/github.com/42wim/matterbridge/gateway/handlers.go:217 +0x1fd
github.com/42wim/matterbridge/gateway.(*Router).handleReceive(0xc4203c6050)
        /home/user/go/src/github.com/42wim/matterbridge/gateway/router.go:141 +0x252
created by github.com/42wim/matterbridge/gateway.(*Router).Start
        /home/user/go/src/github.com/42wim/matterbridge/gateway/router.go:96 +0x838
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdd040b]

goroutine 635 [running]:
github.com/42wim/matterbridge/vendor/github.com/matterbridge/go-xmpp.(*Client).Send(0x0, 0xc420a8b1f8, 0x1c, 0x10cc928, 0x9, 0xc420a8b1d8, 0x17, 0x0, 0x0, 0x0, ...)
        /home/user/go/src/github.com/42wim/matterbridge/vendor/github.com/matterbridge/go-xmpp/xmpp.go:685 +0x32b
github.com/42wim/matterbridge/bridge/xmpp.(*Bxmpp).Send(0xc42045a090, 0xc4205f8ec0, 0xc, 0xc4204f1da0, 0x6, 0xc420623570, 0xb, 0xc4204ee900, 0x12, 0xc42008d140, ...)
        /home/user/go/src/github.com/42wim/matterbridge/bridge/xmpp/xmpp.go:102 +0x5bb
github.com/42wim/matterbridge/gateway.(*Gateway).SendMessage(0xc420503560, 0xc42015e0d0, 0xc4204d5300, 0xc4205b7180, 0x0, 0x0, 0x6, 0xc4204f1d10, 0xb, 0xc4204f1d10)
        /home/user/go/src/github.com/42wim/matterbridge/gateway/gateway.go:444 +0x67b
github.com/42wim/matterbridge/gateway.(*Gateway).handleMessage(0xc420503560, 0xc42015e0d0, 0xc4204d5300, 0x2, 0xc42000f4d8, 0x1)
        /home/user/go/src/github.com/42wim/matterbridge/gateway/handlers.go:217 +0x1fd
github.com/42wim/matterbridge/gateway.(*Router).handleReceive(0xc4203ce050)
        /home/user/go/src/github.com/42wim/matterbridge/gateway/router.go:141 +0x252
created by github.com/42wim/matterbridge/gateway.(*Router).Start
        /home/user/go/src/github.com/42wim/matterbridge/gateway/router.go:96 +0x838
```

**Environment (please complete the following information):**
 - OS: ubuntu 16 lts
 - Matterbridge version: 1.15.0-dev
 - If self compiled: bd0e81f5a0290fbc07a26664d327c09c306b9597

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))

Empty options are anonimized.

```
[discord.x64dbg]
Token=
Server=
RemoteNickFormat="[{PROTOCOL}] {NICK}"

[slack]
[slack.x64dbg]
Token=
RemoteNickFormat="[{PROTOCOL}] {NICK}"

[irc.x64dbg]
Nick=
NickServNick=
NickServPassword=
Server="irc.freenode.net:6697"
UseTLS=true
UseSASL=true
SkipTLSVerify=false
RemoteNickFormat="<{NICK}> "

[gitter.x64dbg]
Token=
RemoteNickFormat="<{NICK}> "
ReplaceMessages=[["^\\[!\\[[^\\]]+\\]\\(https?:\\/\\/files\\.gitter\\.im\\/[^\\/]+\\/[^\\/]+\\/[^\\/]+\\/thumb\\/[^\\)]+\\)\\]\\(([^\\)]+)\\)$", "$1"], ["\\[[^\\]]+\\]\\((https:\\/\\/files\\.gitter\\.im\\/[^\\/]+\\/[^\\/]+\\/[^\\/]+\\/[^\\)]+)\\)$", "$1"]]

[telegram.x64dbg]
Token=
RemoteNickFormat="<{NICK}> "

[xmpp.x64dbg]
Server=
Jid=
Password=
Muc=
Nick=
RemoteNickFormat="<{NICK}> "

[matrix.x64dbg]
Server=
Login=
Password=
RemoteNickFormat="<{NICK}> "
NoHomeServerSuffix=true

[[gateway]]
name="x64dbg"
enable=true

[[gateway.inout]]
account="discord.x64dbg"
channel="x64dbg"
[gateway.inout.options]
WebhookURL=

[[gateway.inout]]
account="slack.x64dbg"
channel="x64dbg"

[[gateway.inout]]
account="irc.x64dbg"
channel="#x64dbg"

[[gateway.inout]]
account="gitter.x64dbg"
channel="x64dbg/x64dbg"

[[gateway.inout]]
account="telegram.x64dbg"
channel=

[[gateway.inout]]
account="xmpp.x64dbg"
channel="x64dbg"

[[gateway.inout]]
account="matrix.x64dbg"
channel="#x64dbg:matrix.org"
```

**Comment by mrexodia** [comment] 2019-06-25 20:40
It happened again. The trick is to just take down the xmpp server it seems and matterbridge will crash.

**Comment by 42wim** [comment] 2019-06-30 15:51
There's this option: https://github.com/42wim/matterbridge/wiki/Settings#ignorefailureonstart
won't fix the xmpp segfaults, but can soften the issue until fixed.

**Closed** 2019-06-30 16:36 UTC
Labels: bug

**Comment by 42wim** [comment] 2019-06-30 16:46
The issue is now fixed (and tested) in master. Please upgrade :-)
Dev binaries can be found on https://bintray.com/42wim/nightly/Matterbridge/v1.15.0-8-gcf3cdda#files

**Comment by mrexodia** [comment] 2019-06-30 17:01
Thank you very much for the quick turnaround time! I’ll test it as soon as
the xmpp server I’m using is back online 🤦‍♂️
