### ISSUE TITLE
Mattermost with WebhookURL doesn't detect it's own messages

### ISSUE THREAD

**Issue by ninja-** [42wim/matterbridge#261] opened 2017-09-17 14:47 UTC
If you have a configuration problem, please first try to create a basic configuration following the instructions on [the wiki](https://github.com/42wim/matterbridge/wiki/How-to-create-your-config) before filing an issue.

Please answer the following questions. 

### Which version of matterbridge are you using?
run ```matterbridge -version```
version: 1.2.0 248d88c

### If you're having problems with mattermost please specify mattermost version. 
4.2

### Please describe the expected behavior.
Messages posted from the webhook should be ignored.

### Please describe the actual behavior. 
When running mattermost bridge with Login+Password PLUS WebhookURL

Messages posted from the WebhookURL are treated as "user messages" and forwarded again.
So if someone types on slack, this message gets forwarded to mattermost and then that message gets forwarded again to slack :|

### Any steps to reproduce the behavior?
1. Setup a mattermost<-> slack pipe.
2. The mattermost config will have a Login/Password user and WebhookURL for posting messages
3. Try sending something first on slack, then something different on mattermost.
4. Observe message being forwarded twice.

#### (be sure to exclude or anonymize private data (tokens/passwords))

Personally I am not sure what's the best way to handle or fix this.
The workaround is simply to skip using webhookURL, but then I can't have fancy "username override" on forwarded posts...

**Comment by 42wim** [comment] 2017-09-18 18:44
I can't reproduce this, could you post your whole config ?
You're using dedicated users for slack and mattermost, right?

**Comment by ninja-** [comment] 2017-09-18 19:02
Right, dedicated users for both, lemme look for the config

**Comment by ninja-** [comment] 2017-09-18 19:04
```
[mattermost]
    [mattermost.x]
    Server="x"
    Team="x"
    Login="matterbridge@example.com"
    Password="x"
WebhookURL="mymattermost.com/hooks/x"
RemoteNickFormat="{NICK}: "
  
 PrefixMessagesWithNick=true
[slack]
	[slack.x]
#Token to connect with the Slack API
#You'll have to use a test/api-token using a dedicated user and not a bot token.
#See https://github.com/42wim/matterbridge/wiki/Slack-bot-setup for more information
	Token="xoxb-xxxxxxxxxxxxxxxxxxxx"
RemoteNickFormat="{NICK} [Matterbridge]"

[[gateway]]
name="x"
enable=true

    [[gateway.inout]]
    account="mattermost.x"
    channel="x"		

    [[gateway.inout]]
    account="slack.x"
    channel="x"
```

**Comment by 42wim** [comment] 2017-09-18 19:23
hmm, I see you use a ```"xoxb-xxxxxxxx"``` token instead of a a ```"xoxp-xxxx"``` token. 
Would it be possible to try with a xoxp token and see if it also happens?

**Comment by 42wim** [comment] 2017-09-18 21:57
Should be fixed in master

**Closed** 2017-09-18 21:57 UTC
