### ISSUE TITLE
[Discord] Join/parts get spammed in "every" gateway that uses Discord

### ISSUE THREAD

**Issue by TomTheDragon** [42wim/matterbridge#727] opened 2019-02-21 14:14 UTC
I do have a rather complex setup with multiple Discord servers, in which i link multiple chats over to other networks.
The problem now is that, when someone joins or parts in one of the connected servers, that message gets send over to "every" gateway, that has an Discord connection attached to it. This also means that those messages also get broadcasted across different servers, which is especially confusing.
I also did not set "ShowJoinPart" to true.

**Comment by Tjird** [comment] 2019-02-21 14:49
I think that you join messages are not the "real" messages from Discord. Why do you have that channel in you list of channels to connect?

**Comment by 42wim** [comment] 2019-02-21 17:14
@TomTheDragon 
I can't reproduce this, is it possible to have the config and possibly a debug log for this?

I have no idea how it's possible to see those messages if you don't have `ShowJoinPart` true, this is checked before a message is sent.

@Tjird seems like the documentation hasn't been updated, I'll fix this. The discord change has been added in a recent commit wrt #654

**Comment by 42wim** [comment] 2019-03-02 21:53
Probably fixed in #743

**Closed by 42wim** 2019-03-02 21:53 UTC
Labels: waiting for feedback

**Comment by TomTheDragon** [comment] 2019-03-04 20:12
This bug is still present in v1.14.0-rc2
