### ISSUE TITLE
WhatsApp Session File is not saved anymore 

### ISSUE THREAD

**Issue by Waldelf** [42wim/matterbridge#1835] opened 2022-05-17 09:35 UTC
**Describe the bug**
With the change to whatsmeow the Sessionfile specified in matterbridge.toml is not written anymore, QR Code has to scanned everytime so that it isn't possible right now to run it as a service.
(Running in docker, compiled with Dockerfile_whatsappmulti)

**To Reproduce**
Build the Dockerfile with:

`docker build https://github.com/42wim/matterbridge.git --file Dockerfile_whatsappmulti`

Create a matterbridge directory with a matterbridge.toml inside:

_[whatsapp.mywhatsapp]
Number="+49178xxxxxxx"
SessionFile="session.gob"
QrOnWhiteTerminal=false
RemoteNickFormat="{NICK} via Bridge: "_

Start docker-container with mounting the session file:
`docker run -v /matterbridge/matterbridge.toml:/matterbridge.toml -v /matterbridge/session.gob:/session.gob 8b58f3ebfef9`

**Expected behavior**
session.gob should be used by matterbridge, session id should be saved inside

**Screenshots/debug logs**
time="2022-05-17T08:37:44Z" level=info msg="Running version 1.25.1 051e6e7" prefix=main
time="2022-05-17T08:37:44Z" level=info msg="Parsing gateway xxxxxx" prefix=router
time="2022-05-17T08:37:44Z" level=info msg="Starting bridge: whatsapp.mywhatsapp " prefix=router
[QR Code]
08:37:47.859 [Client INFO] Successfully paired 49178xxxxxxx.0:20@s.whatsapp.net
time="2022-05-17T08:37:47Z" level=info msg="QR channel result: success" prefix=whatsapp
time="2022-05-17T08:37:48Z" level=info msg="WhatsApp connection successful" prefix=whatsapp
time="2022-05-17T08:37:48Z" level=info msg="Getting user avatars.." prefix=whatsapp
time="2022-05-17T08:37:48Z" level=info msg="Finished getting avatars.." prefix=whatsapp
time="2022-05-17T08:37:48Z" level=info msg="whatsapp.mywhatsapp: joining 49176xxxx-xxxx@g.us (ID: 49176xxxxxx-xxxxxxx@g.uswhatsapp.mywhatsapp)" prefix=whatsapp
08:37:49.312 [Client INFO] Successfully authenticated
08:37:49.895 [Client INFO] Uploading 50 new prekeys to server
08:37:52.239 [Client INFO] Updating contact store with 172 push names from history sync
time="2022-05-17T08:37:52Z" level=info msg="Starting bridge: telegram.mytelegram " prefix=router
time="2022-05-17T08:37:52Z" level=info msg=Connecting prefix=telegram
time="2022-05-17T08:37:52Z" level=info msg="Connection succeeded" prefix=telegram
time="2022-05-17T08:37:53Z" level=info msg="Gateway(s) started succesfully. Now relaying messages" prefix=main

**Environment (please complete the following information):**
 - OS: Linux
 - Matterbridge version: 1.25.1

**Comment by ilmaisin** [comment] 2022-11-11 13:44
Cannot reproduce with 1.25.3-dev.

**Comment by Schmurki** [comment] 2023-01-11 14:20
I observed the same issue. I have to reconnect/pair everytime I restart the bridge.

**Comment by 42wim** [comment] 2023-01-28 23:49
Should be fixed in current master.

**Closed by 42wim** 2023-01-28 23:49 UTC
Labels: bug, whatsapp

**Comment by Schmurki** [comment] 2023-01-29 20:52
I checked it this the current master. I seems to work for my setup.
I have to mount the session file to "session-<ID>.gob.db" in order to store it correctly.

Thank you very much for the fix :)
