### ISSUE TITLE
Gitter bridge fails to start with Status code: 429

### ISSUE THREAD

**Issue by jakubgs** [42wim/matterbridge#921] opened 2019-10-07 11:21 UTC
**Describe the bug**
The Gitter plugin fails to start with following error:
```
Starting gateway failed: Bridge gitter.autobot failed to start: Status code: 429
```

**To Reproduce**
Seems to be related to the large number(20) of Gitter rooms in my configuration.

**Expected behavior**
Maybe delays between calls to avoid hitting the API rate limit?

**Screenshots/debug logs**
I tried running with `-debug` but all I get is the same error as above, nothing more.

**Environment:**
Running `1.15.2` through Docker on Linux.

**Additional context**
According to the internets `429` means [`Too Many Requests`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429).

I've contacted Gitter support to get details on what exactly are the rate limits currently, will update this issue once I get a response.

**Comment by jakubgs** [comment] 2019-10-08 15:34
According to Gitter support their API rate limit is currently set at 100 requests per minute:

The rate limit is 100 requests per minute,

* https://gitlab.com/gitlab-org/gitter/webapp/blob/3e3ed1013a/config/config.prod.json#L8
* https://gitlab.com/gitlab-org/gitter/webapp/blob/3e3ed1013a/server/web/middlewares/rate-limiter.js#L12

Which considering I have only 20 rooms configured must mean that MatterBridge is making `>=5` requests per room at startup. I will try to verify this.

**Comment by 42wim** [comment] 2019-10-26 21:48
Yes, we easily do >= 5 requests per room, we need to get a roomid, join a room, check users in a room, check if we're are ourselves in the room, open a stream to the room.

The issue is an issue in the library we use which doesn't use ratelimiting.

**Comment by jakubgs** [comment] 2019-10-27 12:13
Is it though? All you need is some kind of customizable delay in `Join()`, probably before this:
https://github.com/42wim/matterbridge/blob/bad19901730d51416ebb12882840703e9743502b/bridge/gitter/gitter.go#L60-L63
As far as I know there is no API call in Gitter for checking current limits, like [GitHub's `/rate_limit` call](https://developer.github.com/v3/rate_limit/).

**Comment by 42wim** [comment] 2019-11-15 17:15
@jakubgs all the calls above that code also do API calls.

I'd rather see this in the gitter library itself, but if you're willing to make a PR that fixes it in matterbridge I'm willing to add it.

**Comment by 42wim** [comment] 2020-11-22 20:40
closing as gitter is sold and will be moving to matrix

**Closed by 42wim** 2020-11-22 20:40 UTC
Labels: library issue
