### ISSUE TITLE
Libera.Chat IRC: error: tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by illwieckz** [42wim/matterbridge#1528] opened 2021-06-21 15:27 UTC
**Describe the bug**

Our bridge that worked properly on Libera.Chat IRC stopped to work today, and log is full of errors about TLS.

Maybe they changed something on their infrastructure, but I seen no other users failing to connect at the time, and I doubt all of them don't use TLS.

**To Reproduce**

Just start the bridge with a Libera IRC configuration.

**Expected behavior**

The bridge is expected to connect to this network using TLS.

**Screenshots/debug logs**

```
time="2021-06-21T10:12:32-05:00" level=info msg="Starting bridge: irc.libera " prefix=router
time="2021-06-21T10:12:32-05:00" level=info msg="Connecting irc.libera.chat:6697" prefix=irc
time="2021-06-21T10:12:36-05:00" level=error msg="disconnect: error: tls: first record does not look like a TLS handshake" prefix=irc
time="2021-06-21T10:12:36-05:00" level=fatal msg="Starting gateway failed: Bridge irc.libera failed to start: connection failed tls: first record does not look like a TLS handshake" prefix=main
[…]
time="2021-06-21T10:12:57-05:00" level=fatal msg="Starting gateway failed: Bridge irc.libera failed to start: connection failed EOF" prefix=main
```

Use logs from running `matterbridge -debug` if possible.

**Environment (please complete the following information):**
 - OS: Debian GNU/Linux 9.13 (stretch)
 - Matterbridge version: `1.22.3 e45bbe45` (first got it with `1.22.2 641ed187` then updated, still reproducing)

**Additional context**

Relevant configuration our side looks like this:

```
	[irc.libera]
	Server="irc.libera.chat:6697"
	Nick="dretch"
	NickServNick="REDACTED"
	NickServPassword="REDACTED"
	UseTLS=true
	UseSASL=true
	EditDisable=false
	EditSuffix=" (edited)"
	RemoteNickFormat="<{NICK}> "
	ColorNicks=true
	Charset="utf8"
```

**Comment by poVoq** [comment] 2021-06-21 19:30
Oddly enough our's is still running and connected to libera.chat as I type this. Config seems simliar as well.

I still have that join delay 1000 in it though, as that was a work-around from the freenode days when bridging too many channels. I doubt that is the cause here though.

**Comment by illwieckz** [comment] 2021-06-21 19:46
The bridge disconnected because of a netsplit earlier in the day, but it did not rejoined because of that issue. Maybe already running bridges are not affected?

**Comment by poVoq** [comment] 2021-06-21 19:54
Hmm, possibly. I don't want to restart ours to try ;)

But the only difference in config I see is

`JoinDelay=1000`

**Comment by illwieckz** [comment] 2021-06-22 00:38
The bot joined the channels after 11h30 of erroring.

I restarted just the bridge to see how it behaves and it is erroring again… Maybe it will rejoin in 10 hours…

**Comment by poVoq** [comment] 2021-06-22 12:16
Mine restarted without problems this morning. I guess it was an issue Libera.chat side?

**Comment by qaisjp** [comment] 2021-06-22 14:09
I usually see this error when I'm being rate limited. (When you turn off TLS you might get a more obvious error message.)

**Comment by nhnb** [comment] 2021-06-22 21:49
I have the same "TLS first record" - error a couple of times in my log. Other times, it is just an EOF:

~~~~
time="2021-06-22T00:00:27+02:00" level=info msg="reconnecting in 30 seconds..." func=doConnect file="bridge/irc/irc.go:197" prefix=irc
time="2021-06-22T00:00:57+02:00" level=debug msg="== Receiving PRIVMSG: tungsten.libera.chat *** Checking Ident girc.Event{Source:(*girc.Source)(0xc000a9d860), Tags:girc.Tags(nil), Timestamp:time.Time{wall:0xc02c60e65709e287, ext:273477608120438, loc:(*time.Location)(0x3369100)}, Command:"NOTICE", Params:[]string{"*", "*** Checking Ident"}, Sensitive:false, Echo:false}" func=handlePrivMsg file="bridge/irc/handlers.go:196" prefix=irc
time="2021-06-22T00:00:57+02:00" level=debug msg="== Receiving PRIVMSG: tungsten.libera.chat *** Looking up your hostname... girc.Event{Source:(*girc.Source)(0xc000a9d980), Tags:girc.Tags(nil), Timestamp:time.Time{wall:0xc02c60e6570a7cbf, ext:273477608159870, loc:(*time.Location)(0x3369100)}, Command:"NOTICE", Params:[]string{"*", "*** Looking up your hostname..."}, Sensitive:false, Echo:false}" func=handlePrivMsg file="bridge/irc/handlers.go:196" prefix=irc
time="2021-06-22T00:00:57+02:00" level=debug msg="== Receiving PRIVMSG: tungsten.libera.chat *** Found your hostname: stendhalgame.org girc.Event{Source:(*girc.Source)(0xc000a9daa0), Tags:girc.Tags(nil), Timestamp:time.Time{wall:0xc02c60e6570abc88, ext:273477608176190, loc:(*time.Location)(0x3369100)}, Command:"NOTICE", Params:[]string{"*", "*** Found your hostname: stendhalgame.org"}, Sensitive:false, Echo:false}" func=handlePrivMsg file="bridge/irc/handlers.go:196" prefix=irc
time="2021-06-22T00:00:57+02:00" level=debug msg="detected ISO-8859-1 confidence 75" func=handlePrivMsg file="bridge/irc/handlers.go:221" prefix=irc
time="2021-06-22T00:00:57+02:00" level=debug msg="<= Sending message from * on irc.libera to gateway" func=handlePrivMsg file="bridge/irc/handlers.go:241" prefix=irc
time="2021-06-22T00:00:57+02:00" level=debug msg="detected ISO-8859-1 confidence 23" func=handlePrivMsg file="bridge/irc/handlers.go:221" prefix=irc
time="2021-06-22T00:00:57+02:00" level=debug msg="<= Sending message from * on irc.libera to gateway" func=handlePrivMsg file="bridge/irc/handlers.go:241" prefix=irc
time="2021-06-22T00:00:57+02:00" level=debug msg="detected ISO-8859-1 confidence 39" func=handlePrivMsg file="bridge/irc/handlers.go:221" prefix=irc
time="2021-06-22T00:00:57+02:00" level=debug msg="<= Sending message from * on irc.libera to gateway" func=handlePrivMsg file="bridge/irc/handlers.go:241" prefix=irc
time="2021-06-22T00:01:03+02:00" level=debug msg="== Receiving PRIVMSG: tungsten.libera.chat *** No Ident response girc.Event{Source:(*girc.Source)(0xc0005f25a0), Tags:girc.Tags(nil), Timestamp:time.Time{wall:0xc02c60e7ea9717b1, ext:273483936141683, loc:(*time.Location)(0x3369100)}, Command:"NOTICE", Params:[]string{"*", "*** No Ident response"}, Sensitive:false, Echo:false}" func=handlePrivMsg file="bridge/irc/handlers.go:196" prefix=irc
time="2021-06-22T00:01:03+02:00" level=debug msg="detected ISO-8859-1 confidence 63" func=handlePrivMsg file="bridge/irc/handlers.go:221" prefix=irc
time="2021-06-22T00:01:03+02:00" level=debug msg="<= Sending message from * on irc.libera to gateway" func=handlePrivMsg file="bridge/irc/handlers.go:241" prefix=irc
time="2021-06-22T00:01:05+02:00" level=error msg="disconnect: error: EOF" func=doConnect file="bridge/irc/irc.go:189" prefix=irc
time="2021-06-22T00:01:05+02:00" level=info msg="reconnecting in 30 seconds..." func=doConnect file="bridge/irc/irc.go:197" prefix=irc
~~~~

After a couple of hours of this, the bridge was banned from Libera.

**Comment by 42wim** [comment] 2021-06-22 21:53
Did anyone check with the libera admins yet to ask what has changed? 
Because as everything worked fine before it looks like a libera.chat issue.

**Comment by poVoq** [comment] 2021-06-22 22:08
Maybe the VPS IP range is the issue? Here it is working on Libera.chat without any problems as I type this. Restarting this morning was also smooth.

**Comment by 42wim** [comment] 2021-06-22 22:29
I talked to a libra.chat admin:
- they are using the same ratelimits as on freenode
- nothing has change wrt those ratelimits

They also suggested to batch JOINs (but that's not something easy to change in the current code)

Some questions:
- Can you try to run without TLS for a bit like @qaisjp suggested and see what this shows.
- How many channels are we talking about that you're joining?

**Comment by spb** [comment] 2021-06-22 22:49
There are a couple of cases where the ircd can send an error message in cleartext before starting TLS negotiation, even on a TLS port. Can you get a raw traffic dump (via Wireshark or similar if debug logging can't do it) and see what's actually happening on the TCP connection?

**Comment by nhnb** [comment] 2021-06-23 05:06
I don't think that the IP-address is an issue. Beside the MatterBridge, there is an Irrsi, a PircBotX and an IrcAppender running on the same server. At least the IrcAppender was restarted during the time, the MatterBridge was unable to connect.

Yesterday evening, I disabled the Libera configuration in MatterBridge. And this morning it was able to connect again. It was offline for almost two days.

Perhaps the 30 second reconnect time is too short? As far as I can tell, the issue occurs before MatterBridge tries to join any channels.

**Comment by illwieckz** [comment] 2021-06-25 16:00
The bridge got a netsplit, and it did not rejoined after 13 hours. I added `JoinDelay=1000` to the configuration, restarted the bridge, and it joined immediately. I have not restarted to see if that's reproduceable.

This bot only joins 4 irc channels on libera.chat, there is one or two user irc bouncers on the server, so some other processes may join some other servers as well.

**Comment by 42wim** [comment] 2022-02-05 20:04
Sounds like temporary issue, closing

**Closed by 42wim** 2022-02-05 20:04 UTC
Labels: bug, irc

**Comment by illwieckz** [comment] 2022-02-05 20:29
I confirm I didn't get the bug since that time. On the other hand `JoinDelay=1000` is still set so it's likely to be worked properly around if such temporary issue happens again. So yes that can be safely closed.
