### ISSUE TITLE
Rocket.chat error

### ISSUE THREAD

**Issue by P0ME** [42wim/matterbridge#1073] opened 2020-04-01 09:09 UTC
**Describe the bug**
I have an error with rocket chat stopping forwarding messages.
It works for up to 24 hours then it show this error, the others bridges still works.

**To Reproduce**
I didn't see anyone using rocket.chat with matterbridge, the "official" bridge is broken too.
https://open.rocket.chat/channel/matterbridge.
Not sure it actually work for anyone?

**Screenshots/debug logs**
matterbridge-64[1246]: time="2020-03-31T20:09:37-04:00                                " level=error msg="SendMessage failed: {"details":{"method":"sendMessage"},"erro                                r":"error-invalid-user","errorType":"Meteor.Error","isClientSafe":true,"message"                                :"Invalid user [error-invalid-user]","reason":"Invalid user"}" prefix=gateway

**Environment (please complete the following information):**
Ubuntu 18.04 VPS

Tried that too:
https://github.com/RocketChat/hubot-rocketchat/issues/330
Will see if it works in a few days, if anyone had this error with rocket.chat (or not) please let me know.

**Comment by P0ME** [comment] 2020-04-01 09:10
Tried that too, will see if that work, will see in a few days.

**Comment by 42wim** [comment] 2020-04-04 21:10
Closing in favor of #855 

I disconnected the matterbridge from rocketchat because of those issues.

The problem is the library I'm using https://github.com/RocketChat/Rocket.Chat.Go.SDK and the library that is using https://github.com/gopackage/ddp (which doesn't seem to be maintained anymore).

To fix these issue means changes across those two libraries and the matterbridge rocketchat bridge itself.

I myself don't have time for this at the moment.

**Closed by 42wim** 2020-04-04 21:10 UTC
Labels: bug

**Comment by xavierxross** [comment] 2021-02-20 07:06
> **Describe the bug**
> I have an error with rocket chat stopping forwarding messages.
> It works for up to 24 hours then it show this error, the others bridges still works.
> 
> **To Reproduce**
> I didn't see anyone using rocket.chat with matterbridge, the "official" bridge is broken too.
> https://open.rocket.chat/channel/matterbridge.
> Not sure it actually work for anyone?
> 
> **Screenshots/debug logs**
> matterbridge-64[1246]: time="2020-03-31T20:09:37-04:00 " level=error msg="SendMessage failed: {"details":{"method":"sendMessage"},"erro r":"error-invalid-user","errorType":"Meteor.Error","isClientSafe":true,"message" :"Invalid user [error-invalid-user]","reason":"Invalid user"}" prefix=gateway
> 
> **Environment (please complete the following information):**
> Ubuntu 18.04 VPS
> 
> Tried that too:
> [RocketChat/hubot-rocketchat#330](https://github.com/RocketChat/hubot-rocketchat/issues/330)
> Will see if it works in a few days, if anyone had this error with rocket.chat (or not) please let me know.

I had also got the same error while setting up the rocket.chat bridge...
Btw I've seen the matterbridge rocket.chat bridge last active on 10th feb. maybe, then DeD

**Comment by 42wim** [comment] 2021-02-20 21:18
Are you running the latest version of matterbridge?

**Comment by xavierxross** [comment] 2021-02-22 09:28
> > **Describe the bug**
> > I have an error with rocket chat stopping forwarding messages.
> > It works for up to 24 hours then it show this error, the others bridges still works.
> > **To Reproduce**
> > I didn't see anyone using rocket.chat with matterbridge, the "official" bridge is broken too.
> > https://open.rocket.chat/channel/matterbridge.
> > Not sure it actually work for anyone?
> > **Screenshots/debug logs**
> > matterbridge-64[1246]: time="2020-03-31T20:09:37-04:00 " level=error msg="SendMessage failed: {"details":{"method":"sendMessage"},"erro r":"error-invalid-user","errorType":"Meteor.Error","isClientSafe":true,"message" :"Invalid user [error-invalid-user]","reason":"Invalid user"}" prefix=gateway
> > **Environment (please complete the following information):**
> > Ubuntu 18.04 VPS
> > Tried that too:
> > [RocketChat/hubot-rocketchat#330](https://github.com/RocketChat/hubot-rocketchat/issues/330)
> > Will see if it works in a few days, if anyone had this error with rocket.chat (or not) please let me know.
> 
> I had also got the same error while setting up the rocket.chat bridge...
> Btw I've seen the matterbridge rocket.chat bridge last active on 10th feb. maybe, then DeD

I meant the official matterbridge rocket.chat [channel ](https://open.rocket.chat/channel/matterbridge)
https://i.imgur.com/MfKsutj.png

**Comment by xavierxross** [comment] 2021-02-22 09:29
Latest - [v1.22.0](https://github.com/42wim/matterbridge/releases/download/v1.22.0/matterbridge-1.22.0-linux-64bit)

**Comment by xavierxross** [comment] 2021-03-04 07:40
I used the token instead of Password and it fixed the issue
